package boundary.FormOperazioni;

import boundary.FormDashBoardStudente;
import boundary.FormDashboardDocente;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import controller.GestoreSistema;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class FormLogin {

    private JTextField mailField;
    private JButton loginButton;
    private JTextField passwordField;
    private JPanel LoginFrame;
    private JFrame StudenteDashFrame;
    private JFrame DocenteDashFrame;
    private final GestoreSistema gestoreSistema = GestoreSistema.getInstanza();

    public FormLogin() {
        loginButton.addActionListener(new ActionListener() {
                                          @Override
                                          public void actionPerformed(ActionEvent e) {
                                              String mail = mailField.getText();
                                              String password = passwordField.getText();
                                              int esito = gestoreSistema.autenticazione(mail, password);
                                              if (esito == 0) {
                                                  JOptionPane.showMessageDialog(null,
                                                          "ERRORE: Credenziali non valide",
                                                          "Errore autenticazione!", JOptionPane.ERROR_MESSAGE);
                                              } else if (esito == 2) {
                                                  JOptionPane.showMessageDialog(null,
                                                          "Benvenuto " + gestoreSistema.getCurrentUtente().getNome() + "! Verrai reindirizzato alla dashboard...",
                                                          "Login effettuato", JOptionPane.INFORMATION_MESSAGE);
                                                  Window window = SwingUtilities.getWindowAncestor(LoginFrame);
                                                  if (window != null) window.dispose();
                                                  if (StudenteDashFrame == null || !StudenteDashFrame.isDisplayable()) {
                                                      FormDashBoardStudente formDashBoardStudente = new FormDashBoardStudente();
                                                      StudenteDashFrame = formDashBoardStudente.apriFormDashBoardStudente();
                                                  }
                                                  else {
                                                      StudenteDashFrame.toFront();
                                                      StudenteDashFrame.requestFocus();
                                                  }
                                              } else if (esito == 1) {

                                                  JOptionPane.showMessageDialog(null,
                                                          "Benvenuto " + gestoreSistema.getCurrentUtente().getNome() + "! Verrai reindirizzato alla dashboard...",
                                                          "Login effettuato", JOptionPane.INFORMATION_MESSAGE);
                                                  Window window = SwingUtilities.getWindowAncestor(LoginFrame);
                                                  if (window != null) window.dispose();
                                                  if (DocenteDashFrame == null || !DocenteDashFrame.isDisplayable()) {
                                                      FormDashboardDocente formDashBoardDocente = new FormDashboardDocente();
                                                      DocenteDashFrame = formDashBoardDocente.apriDashDocente();
                                                  }
                                                  else {
                                                    DocenteDashFrame.toFront();
                                                    DocenteDashFrame.requestFocus();
                                                  }
                                              }
                                          }
                                      }


        );
    }


    public JFrame apriFormLogin() {

        JFrame frame = new JFrame("Inserisci Credenziali...");
        frame.setContentPane(LoginFrame);

        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        frame.setResizable(false);
        frame.setSize(500, 200);
        return frame;

    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        LoginFrame = new JPanel();
        LoginFrame.setLayout(new GridLayoutManager(8, 4, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Inserisci E-mail e Password");
        LoginFrame.add(label1, new GridConstraints(1, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        LoginFrame.add(panel1, new GridConstraints(0, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("E-Mail");
        LoginFrame.add(label2, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(39, 17), null, 0, false));
        mailField = new JTextField();
        LoginFrame.add(mailField, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        LoginFrame.add(panel2, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Password");
        LoginFrame.add(label3, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(39, 17), null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        LoginFrame.add(panel3, new GridConstraints(5, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        LoginFrame.add(panel4, new GridConstraints(3, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        LoginFrame.add(panel5, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        loginButton = new JButton();
        loginButton.setText("Login");
        LoginFrame.add(loginButton, new GridConstraints(6, 2, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        LoginFrame.add(panel6, new GridConstraints(7, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        passwordField = new JTextField();
        LoginFrame.add(passwordField, new GridConstraints(4, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return LoginFrame;
    }

}
