package boundary.FormOperazioni;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import controller.GestoreSistema;
import database.DTO.CorsoDTO;
import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.Year;

public class FormCreaCorso {
    private JPanel CreaCorsoFrame;
    private JTextField textField1;
    private JTextPane DescrTextPane;
    private JTextField TitoloField;
    private JButton ConfermaButton;
    private JCheckBox AnnoAccademicoCheckBox;
    private boolean AutoGeneraAnnoAccademico = false;
    private final GestoreSistema gestoreSistema = GestoreSistema.getInstanza();
    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }


    public FormCreaCorso(){

        AnnoAccademicoCheckBox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if(AnnoAccademicoCheckBox.isSelected()) AutoGeneraAnnoAccademico = true;
            }
        });


        ConfermaButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String titolo = TitoloField.getText();
                String codice = textField1.getText();
                String descr = DescrTextPane.getText();
                String annoAcc;
                if(AutoGeneraAnnoAccademico){
                     annoAcc = Year.now().getValue() + "/" + (Year.now().getValue()+1);
                }
                else{annoAcc = "";}


                int esito = gestoreSistema.validaDatiCorso(titolo, descr, codice, annoAcc);
                if (esito == 0) {
                    JOptionPane.showMessageDialog(null, "Titolo vuoto o troppo lungo!");
                    return;
                }
                if (esito==1) {
                    JOptionPane.showMessageDialog(null, "Descrizione vuota o troppo lunga!");
                    return;
                }
                if (esito==2) {
                    JOptionPane.showMessageDialog(null, "Codice non numerico o già in utilizzo!");
                    return;
                }

                if(esito==4){

                CorsoDTO corso = new CorsoDTO();
                corso.setTitolo(titolo);
                corso.setCodice(Integer.parseInt(codice));//safe, perchè a questo punto ho già superato il controllo validità
                corso.setDescr(descr);
                corso.setAnnoAccademico(annoAcc);

                if (gestoreSistema.CreaCorso(corso)){
                    JOptionPane.showMessageDialog(null,
                            "Creazione avvenuta con successo, premi su Aggiorna per visualizzare il nuovo corso in lista",
                            "Corso Creato", JOptionPane.INFORMATION_MESSAGE);
                    Window window = SwingUtilities.getWindowAncestor(CreaCorsoFrame);
                    if (window != null) window.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null,
                        "Creazione Fallita, Riprovare",
                        "Corso Non Creato", JOptionPane.ERROR_MESSAGE);}

            }}
        });





    }

    public JFrame ApriFormCreaCorso(){

        JFrame frame = new JFrame("Crea nuovo Corso");
        frame.setContentPane(CreaCorsoFrame);

        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        frame.setResizable(true);
        return frame;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        CreaCorsoFrame = new JPanel();
        CreaCorsoFrame.setLayout(new GridLayoutManager(9, 4, new Insets(0, 0, 0, 0), -1, -1));
        CreaCorsoFrame.setMinimumSize(new Dimension(900, 460));
        CreaCorsoFrame.setBorder(BorderFactory.createTitledBorder(BorderFactory.createRaisedBevelBorder(), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JLabel label1 = new JLabel();
        label1.setText("Inserisci Dati");
        CreaCorsoFrame.add(label1, new GridConstraints(1, 1, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Titolo del Corso");
        CreaCorsoFrame.add(label2, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Codice Univoco");
        CreaCorsoFrame.add(label3, new GridConstraints(4, 1, 2, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("Descrizione");
        CreaCorsoFrame.add(label4, new GridConstraints(7, 1, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textField1 = new JTextField();
        CreaCorsoFrame.add(textField1, new GridConstraints(5, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        DescrTextPane = new JTextPane();
        CreaCorsoFrame.add(DescrTextPane, new GridConstraints(7, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        CreaCorsoFrame.add(panel1, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        CreaCorsoFrame.add(panel2, new GridConstraints(8, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        ConfermaButton = new JButton();
        ConfermaButton.setText("Crea Corso");
        panel2.add(ConfermaButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel2.add(spacer1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        CreaCorsoFrame.add(panel3, new GridConstraints(7, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        CreaCorsoFrame.add(panel4, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JSeparator separator1 = new JSeparator();
        CreaCorsoFrame.add(separator1, new GridConstraints(6, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        TitoloField = new JTextField();
        CreaCorsoFrame.add(TitoloField, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JSeparator separator2 = new JSeparator();
        CreaCorsoFrame.add(separator2, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return CreaCorsoFrame;
    }

}
