package boundary;
import boundary.FormOperazioni.FormCreaCorso;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import controller.GestoreSistema;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;


public class FormDashboardDocente {


    private JPanel DashDocentePanel;
    private JButton creaNuovoCorsoButton;
    private JList<String> listaCorsi;
    private JButton creaNuovaSezioneButton;
    private JButton iscriviStudente;
    private JButton pubMatButton;
    private JButton modMatButton;
    private JButton delMatButton;
    private JButton viewStatsButton;
    private JButton ricercaButton;
    private JButton logOutButton;
    private JLabel nomeCognomeLabel;
    private JButton AggiornaButton;
    private ArrayList<String> righe;
    private DefaultListModel<String> model;
    private final GestoreSistema gestoreSistema = GestoreSistema.getInstanza();
    private JFrame CreaCorsoFrame;


    public FormDashboardDocente() {

        nomeCognomeLabel.setText(gestoreSistema.getCurrentUtente().getNome() + " " + gestoreSistema.getCurrentUtente().getCognome());
        caricaListaCorsi();

        listaCorsi.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                aggiornaStatoPulsantidelCorso();
            }
        });
        logOutButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                gestoreSistema.logOut();
                Window window = SwingUtilities.getWindowAncestor(DashDocentePanel);
                if (window != null) window.dispose();

            }
        });

        creaNuovoCorsoButton.addActionListener(new ActionListener() {
                                                   @Override
                                                   public void actionPerformed(ActionEvent e) {
                                                       if (CreaCorsoFrame == null || !CreaCorsoFrame.isDisplayable()) {
                                                           FormCreaCorso formCreaCorso = new FormCreaCorso();
                                                           CreaCorsoFrame = formCreaCorso.ApriFormCreaCorso();
                                                       }
                                                   }
                                               }
        );

        AggiornaButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                caricaListaCorsi();
            }
        });
    }

    private void aggiornaStatoPulsantidelCorso() {//questo metodo abilita specifici tasti solo se è selezionato un corso
        boolean corsoSelezionato = !listaCorsi.isSelectionEmpty();
        creaNuovaSezioneButton.setEnabled(corsoSelezionato);
        pubMatButton.setEnabled(corsoSelezionato);
        modMatButton.setEnabled(corsoSelezionato);
        delMatButton.setEnabled(corsoSelezionato);
        iscriviStudente.setEnabled(corsoSelezionato);
        viewStatsButton.setEnabled(corsoSelezionato);
    }

    public void caricaListaCorsi() {
        righe = new ArrayList<>(gestoreSistema.caricaListaCorsiUtente());
        model = new DefaultListModel<>();
        model.addAll(righe);
        listaCorsi.setModel(model);
    }

    public JFrame apriDashDocente() {

        JFrame frame = new JFrame("WIP");
        frame.setContentPane(DashDocentePanel);

        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        frame.setResizable(true);
        return frame;

    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        DashDocentePanel = new JPanel();
        DashDocentePanel.setLayout(new GridLayoutManager(15, 4, new Insets(0, 0, 0, 0), -1, -1));
        DashDocentePanel.setMinimumSize(new Dimension(500, 400));
        DashDocentePanel.setPreferredSize(new Dimension(500, 400));
        DashDocentePanel.setRequestFocusEnabled(true);
        final JLabel label1 = new JLabel();
        label1.setText("Area Docenti di:");
        DashDocentePanel.add(label1, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("I tuoi Corsi:");
        DashDocentePanel.add(label2, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        creaNuovoCorsoButton = new JButton();
        creaNuovoCorsoButton.setText("Crea Nuovo Corso");
        DashDocentePanel.add(creaNuovoCorsoButton, new GridConstraints(4, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        listaCorsi = new JList();
        final DefaultListModel defaultListModel1 = new DefaultListModel();
        listaCorsi.setModel(defaultListModel1);
        listaCorsi.setSelectionMode(1);
        DashDocentePanel.add(listaCorsi, new GridConstraints(4, 1, 8, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        creaNuovaSezioneButton = new JButton();
        creaNuovaSezioneButton.setEnabled(false);
        creaNuovaSezioneButton.setText("Crea Nuova Sezione");
        creaNuovaSezioneButton.setToolTipText("Seleziona prima un Corso");
        DashDocentePanel.add(creaNuovaSezioneButton, new GridConstraints(5, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        iscriviStudente = new JButton();
        iscriviStudente.setEnabled(false);
        iscriviStudente.setText("Iscrivi Studente ");
        iscriviStudente.setToolTipText("Seleziona prima un corso");
        DashDocentePanel.add(iscriviStudente, new GridConstraints(6, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        pubMatButton = new JButton();
        pubMatButton.setEnabled(false);
        pubMatButton.setText("Pubblica Materiale Didattico");
        pubMatButton.setToolTipText("Seleziona prima un Corso");
        DashDocentePanel.add(pubMatButton, new GridConstraints(7, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        modMatButton = new JButton();
        modMatButton.setEnabled(false);
        modMatButton.setText("Modifica Materiale Didattico");
        modMatButton.setToolTipText("Seleziona prima un Corso");
        DashDocentePanel.add(modMatButton, new GridConstraints(8, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        delMatButton = new JButton();
        delMatButton.setEnabled(false);
        delMatButton.setText("Rimuovi Materiale");
        delMatButton.setToolTipText("Seleziona prima un Corso");
        DashDocentePanel.add(delMatButton, new GridConstraints(9, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        viewStatsButton = new JButton();
        viewStatsButton.setEnabled(false);
        viewStatsButton.setText("Vedi Statistiche Corso");
        viewStatsButton.setToolTipText("Seleziona prima un Corso");
        DashDocentePanel.add(viewStatsButton, new GridConstraints(10, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ricercaButton = new JButton();
        ricercaButton.setText("Cerca");
        DashDocentePanel.add(ricercaButton, new GridConstraints(11, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        logOutButton = new JButton();
        logOutButton.setText("Logout");
        DashDocentePanel.add(logOutButton, new GridConstraints(13, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JSeparator separator1 = new JSeparator();
        DashDocentePanel.add(separator1, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Seleziona un corso per usufruire di tutte le funzioni");
        DashDocentePanel.add(label3, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        DashDocentePanel.add(panel1, new GridConstraints(3, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        DashDocentePanel.add(panel2, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        DashDocentePanel.add(panel3, new GridConstraints(14, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        DashDocentePanel.add(panel4, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JSeparator separator2 = new JSeparator();
        DashDocentePanel.add(separator2, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        nomeCognomeLabel = new JLabel();
        nomeCognomeLabel.setText("placeholder");
        DashDocentePanel.add(nomeCognomeLabel, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        AggiornaButton = new JButton();
        AggiornaButton.setText("Aggiorna Lista Corsi");
        DashDocentePanel.add(AggiornaButton, new GridConstraints(12, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return DashDocentePanel;
    }

}
