package boundary;
import boundary.FormOperazioni.FormIscrivitiACorso;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import controller.GestoreSistema;

import javax.swing.*;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

public class FormDashBoardStudente {
    private JPanel DashStudentePanel;
    private JLabel nomeCognomeLabel;
    private JList<String> listaCorsi;
    private JButton iscrivitiACorsoButton;
    private JButton consultaMaterialeButton;
    private JButton cercaProfiloDocenteButton;
    private JButton notificheButton;
    private JButton logoutButton;
    private JButton AggiornaListaButton;
    private JFrame FrameIscrivitiaCorso;
    private int codice;
    private ArrayList<String> righe;
    private DefaultListModel<String> model;
    private final GestoreSistema gestoreSistema = GestoreSistema.getInstanza();

    public FormDashBoardStudente() {

        nomeCognomeLabel.setText(gestoreSistema.getCurrentUtente().getNome() + " " + gestoreSistema.getCurrentUtente().getCognome());
        caricaListaCorsi();

        listaCorsi.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                aggiornaStatoPulsantidelCorso();
            }
        });

        AggiornaListaButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                caricaListaCorsi();
            }
        });

        iscrivitiACorsoButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                if (FrameIscrivitiaCorso == null || !FrameIscrivitiaCorso.isDisplayable()) {
                    FormIscrivitiACorso formIscrivitiACorso = new FormIscrivitiACorso();
                    FrameIscrivitiaCorso = formIscrivitiACorso.apriFormIscrivitiACorso();
                } else {
                    FrameIscrivitiaCorso.toFront();
                    FrameIscrivitiaCorso.requestFocus();
                }
            }
        });

        logoutButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                gestoreSistema.logOut();
                Window window = SwingUtilities.getWindowAncestor(DashStudentePanel);
                if (window != null) window.dispose();

            }
        });
    }


    private void aggiornaStatoPulsantidelCorso() {//questo metodo abilita specifici tasti solo se è selezionato un corso
        boolean corsoSelezionato = !listaCorsi.isSelectionEmpty();
        consultaMaterialeButton.setEnabled(corsoSelezionato);
    }

    public void caricaListaCorsi() {
        righe = new ArrayList<>(gestoreSistema.caricaListaCorsiUtente());
        model = new DefaultListModel<>();
        model.addAll(righe);
        listaCorsi.setModel(model);
    }


    public JFrame apriFormDashBoardStudente() {

        JFrame frame = new JFrame("DashBoardStudente");
        frame.setContentPane(DashStudentePanel);

        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        frame.setResizable(true);
        return frame;

    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        DashStudentePanel = new JPanel();
        DashStudentePanel.setLayout(new GridLayoutManager(11, 4, new Insets(0, 0, 0, 0), -1, -1));
        DashStudentePanel.setMinimumSize(new Dimension(500, 400));
        DashStudentePanel.setPreferredSize(new Dimension(500, 400));
        final JLabel label1 = new JLabel();
        label1.setText("Area Personale di:");
        DashStudentePanel.add(label1, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        nomeCognomeLabel = new JLabel();
        nomeCognomeLabel.setText("placeholder");
        DashStudentePanel.add(nomeCognomeLabel, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        listaCorsi = new JList();
        listaCorsi.setSelectionMode(0);
        DashStudentePanel.add(listaCorsi, new GridConstraints(4, 1, 4, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        final JSeparator separator1 = new JSeparator();
        DashStudentePanel.add(separator1, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JSeparator separator2 = new JSeparator();
        DashStudentePanel.add(separator2, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Sei Iscritto ai seguenti Corsi:");
        DashStudentePanel.add(label2, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        iscrivitiACorsoButton = new JButton();
        iscrivitiACorsoButton.setText("Iscriviti a un Corso");
        DashStudentePanel.add(iscrivitiACorsoButton, new GridConstraints(4, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        consultaMaterialeButton = new JButton();
        consultaMaterialeButton.setEnabled(false);
        consultaMaterialeButton.setText("Consulta materiali disponibili");
        consultaMaterialeButton.setToolTipText("Seleziona prima un corso");
        DashStudentePanel.add(consultaMaterialeButton, new GridConstraints(5, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cercaProfiloDocenteButton = new JButton();
        cercaProfiloDocenteButton.setText("Cerca Profilo Docente");
        DashStudentePanel.add(cercaProfiloDocenteButton, new GridConstraints(6, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        notificheButton = new JButton();
        notificheButton.setText("Notifiche");
        DashStudentePanel.add(notificheButton, new GridConstraints(7, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        logoutButton = new JButton();
        logoutButton.setText("Logout");
        DashStudentePanel.add(logoutButton, new GridConstraints(9, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        DashStudentePanel.add(panel1, new GridConstraints(4, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        DashStudentePanel.add(panel2, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        DashStudentePanel.add(panel3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        DashStudentePanel.add(panel4, new GridConstraints(10, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        AggiornaListaButton = new JButton();
        AggiornaListaButton.setText("Aggiorna Lista Corsi");
        DashStudentePanel.add(AggiornaListaButton, new GridConstraints(8, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return DashStudentePanel;
    }

}
